### PR TITLE
Refactor site deployment to netlify

### PR DESCRIPTION
**Pull request by literarymachine**
Site is now proxied to netlify. In order for the preview builds to work on `*.rightsstatements.org` subdomains, DNS has be configured accordingly. Also, a wildcard certificate is required. Proxying the preview URLs to `rights-app` allows the app to load handlebars templates from the corresponding subdomain.

### CODE REVIEW

**Review by aisaac — COMMENTED** [review]
Honestly @literarymachine goes beyond my expertise. It looks good, but that is based on what you introduced in our call, not on my analysis of the code in this PR!
Well I've actually checked it, and it seems to implement what we've agreed to, but I can't warrant it :-)

**Comment by literarymachine** [comment]
8e4da4e configures in such a way that Netlify [proxies](https://www.netlify.com/docs/redirects/#proxying) requests to our rights-app server instead of vice versa. This will require updating the [DNS](https://www.netlify.com/docs/custom-domains/).

**Review by anarchivist — COMMENTED** [review]
As discussed on the call, this sounds good to me. Thanks!

**Comment by literarymachine** [comment]
@anarchivist feel free to merge. I will deploy things once the DNS is updated; we'll be in touch to schedule that!

**Pull request merged**
